# Property declarations common to all environments
spring:
  main:
    web-environment: true

  data:
    mongodb:
      host: 192.168.99.100
      database: fullstackstarter

server:
    port: 4000
# Property overrides specific to an environment
---
spring:
  profiles: local

  data:
    mongodb:
      host: 192.168.99.100
      database: fullstackstarter
